[package]
name = "macho"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.8.0"
nom = "8.0.0"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
strum = "0.26.3"
strum_macros = "0.26.4"
uuid = "1.13.1"
